### ISSUE TITLE
Running jar file throws error: index.html file not found

### ISSUE THREAD

**Issue by 22phuber** [22phuber/tron-light-cycles#3]
Der Pfad stimmt nicht weil der Pfad relativ ist.

Error snippet: 
```bash
❯ java -classpath tron.jar gameserver.GameServer
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by io.netty.util.internal.ReflectionUtil (file:/Users/phuber/git/tron-light-cycles/app/out/artifacts/tron_jar/tron.jar) to constructor java.nio.DirectByteBuffer(long,int)
WARNING: Please consider reporting this to the maintainers of io.netty.util.internal.ReflectionUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Game Loop running
java.io.FileNotFoundException: /Users/phuber/git/tron-light-cycles/app/out/src/main/resources/static/index.html (No such file or directory)
	at java.base/java.io.RandomAccessFile.open0(Native Method)
	at java.base/java.io.RandomAccessFile.open(RandomAccessFile.java:347)
	at java.base/java.io.RandomAccessFile.<init>(RandomAccessFile.java:261)
	at java.base/java.io.RandomAccessFile.<init>(RandomAccessFile.java:216)
	at gameserver.config.HttpRequestHandler.channelRead0(HttpRequestHandler.java:30)
	at gameserver.config.HttpRequestHandler.channelRead0(HttpRequestHandler.java:11)
…
```

**Comment by 22phuber** [comment]
Absoluter Pfad hat das Problem gelöst: 
```
final String indexRelativeURI = "/Users/phuber/git/tron-light-cycles/app/src/main/resources/static/index.html";
```
Aber so kann ich den Code nicht commiten
